Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -105,14 +105,14 @@ jobs:
               sudo apt update && sudo apt install -y nodejs npm
             fi
 
-            if ! command -v pm2 &> /dev/null; then
-              echo "pm2 could not be found, installing..."
-              sudo npm install -g pm2
+            if ! command -v forever &> /dev/null; then
+              echo "forver could not be found, installing..."
+              npm install -g forever
             fi
 
             # Deployment commands
             cd ~/fleet-managment-system
             npm install
-            pm2 stop all || true
-            pm2 start index.js
+            forever stopall
+            forever start index.js
           EOF
